modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
[[mods]]
modId="createdynlight"
version="${version}"
displayName="Create Dynamic Light"
logoFile="icon.png"
authors="Leon"
description='''
Add dynamic lights to the Create mod.
'''
[[dependencies.createdynlight]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.createdynlight]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.createdynlight]]
    modId="create"
    mandatory=true
    versionRange="[0.5.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.createdynlight]]
    modId="dynamiclightsreforged"
    mandatory=false
    versionRange="[1.6.0,)"
    ordering="AFTER"
    side="BOTH"
