# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Publish Jar

on:
  workflow_dispatch:

env:
  JAVA_VERSION: 17

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build

#      - name: Publish Fabric
#        uses: Kir-Antipov/mc-publish@v3.3
#        with:
#          curseforge-id: 659897
#          curseforge-token: "${{secrets.CURSEFORGE_TOKEN}}"
#
#          modrinth-id: iris-flw-compat
#          modrinth-token: "${{secrets.MODRINTH_TOKEN}}"
#
#          github-token: "${{secrets.PUBLISH_TOKEN}}"
#
#          name: Fabric 1.20.1-1.1.0 for Iris 1.7.0+
#          changelog-file: CHANGELOG.md
#
#          java: "${{env.JAVA_VERSION}}"
#          files: fabric/build/libs/!(*-dev|*-sources|*-javadoc|*-shadow).jar
#
#          dependencies: |
#            IrisShader@1.7.0(required){modrinth:iris}{curseforge:455508}
#            CreateFabric(optional){modrithn:create-fabric}{curseforge:624165}
#
#          fail-mode: warn


      - name: Publish Forge
        uses: Kir-Antipov/mc-publish@v3.3
        with:
#          curseforge-id: 659897
#          curseforge-token: "${{secrets.CURSEFORGE_TOKEN}}"

#          modrinth-id: iris-flw-compat
#          modrinth-token: "${{secrets.MODRINTH_TOKEN}}"

          github-token: "${{secrets.PUBLISH_TOKEN}}"

#          name: Forge 1.20.1-1.1.0
          changelog-file: CHANGELOG.md

          java: "${{env.JAVA_VERSION}}"
          files: forge/build/libs/!(*-dev|*-sources|*-javadoc|*-shadow).jar

          fail-mode: warn
